### PR TITLE
Update README to include setup/test instructions

### PR DESCRIPTION
**Pull request by mosic**

### CODE REVIEW

**Comment by eolszewski** [comment]
@mosic I am attempting to run these tests locally with the README you've included here and am running into the following issue on every test in `__tests__/erebos-api-bzz-base.js`:

```
Expected: "https://example.com/swarm-gateways/bzz:/abcdef123456"
Received: "https://example.com/swarm-gateways//bzz:/abcdef123456"
```

**Comment by eolszewski** [comment]
In `__tests__/erebos-api-bzz-node.js`, I get the following:

`Bzz › uploading and downloading single file using bzz`
`FetchError: request to http://bzz/ef336589675ff5bb3ae74f4d80155a74fa88ccaf1f0b66aba59d73579ef6bd23/ failed, reason: getaddrinfo ENOTFOUND bzz bzz:80`

`uploading and downloading single file using bzz with content path`
`TypeError: bzz.downloadBuffer is not a function`

`uploading and downloading single file using bzz using Buffer type`
`FetchError: request to http://bzz/0be9ce2e6a37bdc076b30e1e6143c07daeae227dcefb1ce05e44b51962e761de/ failed, reason: getaddrinfo ENOTFOUND bzz bzz:80`

**Comment by eolszewski** [comment]
Given that these are running fine in circle, I can only assume that there is a problem with my local development environment. @PaulLeCam can you attempt this as well and see if you get similar results?

**Comment by mosic** [comment]
I just tried going through the steps I described on another machine and everything indeed went ok.

From the errors you shared, to me it looks like the tests are somehow loading the versions of `erebos-*` libraries from npm, instead of the local ones (because e.g. `downloadBuffer` function was recently added (https://github.com/MainframeHQ/erebos/commit/edbefb80148fcd065426112e866073d6d6abb724) and is present on the master branch, but is not in a released version of erebos yet).

Paul might have better suggestions, but until then you can try ensuring that you're on the latest commit of the master
branch, deleting `node_modules` directory, and possibly removing erebos libraries if you installed them globally for some reason.

**Comment by PaulLeCam** [comment]
@eolszewski have you run `yarn bootstrap` and `yarn build` before running the tests?
I just tried again following the steps documented in this PR and it works as expected. I don't think the tests would accidentally use the modules from npm, but from the errors you're having it seems they're not running the latest version of the code.

**Comment by eolszewski** [comment]
The latest version of node is incompatible with a lot of project and tooling in the space, we've found `v8.9.4` to work with most things.

**Comment by PaulLeCam** [comment]
node 8 should work, I was talking about the latest version of the **code**, not node, making sure you're using the latest master and running `yarn build` so the code matches the tests expectations.

**Comment by mosic** [comment]
FWIW I tried going through setup/tests on both `v8.9.4` and `v10.1.0`, and both worked fine.

**Comment by eolszewski** [comment]
These are all working, sorry for the confusion. I had pulled this down a few days ago and ran the yarn commands but do not believe that I had re-run them after pulling down the latest updates.

**Pull request merged**
